### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by introt** [HorseLuvver/zim-auto-linker#2]
Hi! I was planning on writing a similar plugin, and would like to contribute to yours instead. Could you [add a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) which allows me to do so? Zim uses GPLv2, some prefer MIT, visit [choosealicense.com](https://choosealicense.com/) to learn more. Thank you!

**Comment by auralluring** [comment]
I've added a license, but I actually switched to Obsidian a little while ago and don't plan on updating the plugin at all. It would be easier if I just transfer ownership to you.

**Comment by introt** [comment]
Thanks! In that case, I'd prefer to just fork as some people are already using your plugin as-is and I don't want to break their workflows.
